/**
 * Phase 1 E2E Integration Test: Video Streaming Pipeline
 *
 * Two test suites:
 *   1. "Sanity" — downloads small fixture fully, then parses (existing behavior)
 *   2. "Blocking reads" — starts parsing concurrently with a throttled download,
 *      proving that TorrentSource._read() blocks and resumes as pieces arrive.
 *
 * Prerequisites:
 *   - Python with libtorrent (uv sync in integration/python/)
 *   - test-h264-aac.mp4 fixture in integration/streaming/fixtures/
 *   - test-video-long.mp4 generated by fixtures/generate-fixtures.sh
 */
import { execFileSync, spawn, type ChildProcess } from 'node:child_process'
import { existsSync, readFileSync } from 'node:fs'
import { join } from 'node:path'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { ALL_FORMATS, EncodedPacketSink, Input, Source, type EncodedPacket } from 'mediabunny'

import { BtEngine } from '../../src/core/bt-engine'
import type { Torrent } from '../../src/core/torrent'
import { InMemoryFileSystem, MemorySessionStore } from '../../src/adapters/memory'
import { NodeSocketFactory, NodeHasher } from '../../src/adapters/node'
import { StorageRootManager } from '../../src/storage/storage-root-manager'
import { MemoryConfigHub } from '../../src/config/memory-config-hub'
import { createTorrentSource } from '../../src/streaming/torrent-source'

const FIXTURES_DIR = join(import.meta.dirname, 'fixtures')
const PYTHON_DIR = join(import.meta.dirname, '..', 'python')
const MP4_SMALL = join(FIXTURES_DIR, 'test-h264-aac.mp4')
const MP4_LONG = join(FIXTURES_DIR, 'test-video-long.mp4')

interface SeederResult {
  proc: ChildProcess
  magnet: string
  infoHash: string
}

/**
 * Start the Python seeder for a file.
 * @param file - Path to the file to seed
 * @param uploadLimit - Upload rate limit in bytes/sec (0 = unlimited)
 */
function startSeeder(file: string, uploadLimit = 0): Promise<SeederResult> {
  return new Promise((resolve, reject) => {
    const args = [
      'run',
      'python',
      '-u', // Unbuffered stdout
      'seed_for_test.py',
      '--file',
      file,
      '--port',
      '0',
      '--host',
      '127.0.0.1',
      '--bind',
      '127.0.0.1',
      '--quiet',
    ]
    if (uploadLimit > 0) {
      args.push('--upload-limit', String(uploadLimit))
    }

    const proc = spawn('uv', args, {
      cwd: PYTHON_DIR,
      stdio: ['ignore', 'pipe', 'pipe'],
    })

    let stdout = ''
    let stderr = ''

    proc.stdout!.on('data', (data: Buffer) => {
      stdout += data.toString()

      const magnetMatch = stdout.match(/^MAGNET_LOCALHOST=(.+)$/m)
      const hashMatch = stdout.match(/^INFOHASH=(.+)$/m)
      if (magnetMatch && hashMatch) {
        resolve({
          proc,
          magnet: magnetMatch[1],
          infoHash: hashMatch[1],
        })
      }
    })

    proc.stderr!.on('data', (data: Buffer) => {
      stderr += data.toString()
    })

    proc.on('error', (err) => {
      reject(new Error(`Failed to start seeder: ${err.message}`))
    })

    proc.on('exit', (code) => {
      if (code !== 0 && code !== null) {
        reject(new Error(`Seeder exited with code ${code}: ${stderr}`))
      }
    })

    setTimeout(() => {
      reject(new Error(`Seeder startup timeout. stdout: ${stdout}, stderr: ${stderr}`))
    }, 30000)
  })
}

function createEngine(opts?: { downloadLimit?: number }): BtEngine {
  const storageRootManager = new StorageRootManager(() => new InMemoryFileSystem())
  storageRootManager.addRoot({ key: 'memory', label: 'Memory', path: '/memory' })
  storageRootManager.setDefaultRoot('memory')

  let config: MemoryConfigHub | undefined
  if (opts?.downloadLimit) {
    config = new MemoryConfigHub({
      downloadSpeedUnlimited: false,
      downloadSpeedLimit: opts.downloadLimit,
    })
    void config.init()
  }

  return new BtEngine({
    socketFactory: new NodeSocketFactory(),
    storageRootManager,
    sessionStore: new MemorySessionStore(),
    hasher: new NodeHasher(),
    port: 0,
    config,
  })
}

function waitForComplete(torrent: Torrent, timeoutMs = 30000): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    if (torrent.isComplete) {
      resolve()
      return
    }
    const timeout = setTimeout(
      () =>
        reject(
          new Error(
            `Download timeout. Progress: ${torrent.completedPiecesCount}/${torrent.piecesCount}`,
          ),
        ),
      timeoutMs,
    )
    torrent.on('complete', () => {
      clearTimeout(timeout)
      resolve()
    })
  })
}

// ─── Suite 1: Sanity (small fixture, download-then-parse) ────────────────────

describe('Streaming Pipeline E2E', () => {
  let seederProc: ChildProcess
  let engine: BtEngine
  let torrent: Torrent

  beforeAll(async () => {
    const seeder = await startSeeder(MP4_SMALL)
    seederProc = seeder.proc
    engine = createEngine()

    const { torrent: t } = await engine.addTorrent(seeder.magnet)
    if (!t) throw new Error('Failed to add torrent')
    torrent = t

    await waitForComplete(torrent)
  }, 45000)

  afterAll(async () => {
    if (seederProc && !seederProc.killed) seederProc.kill('SIGTERM')
    if (engine) await engine.destroy()
  })

  it('downloads the MP4 fixture completely', () => {
    expect(torrent.isComplete).toBe(true)
    expect(torrent.piecesCount).toBeGreaterThan(0)
    expect(torrent.completedPiecesCount).toBe(torrent.piecesCount)
    expect(torrent.files.length).toBe(1)
    expect(torrent.files[0].length).toBe(readFileSync(MP4_SMALL).length)
  })

  it('creates TorrentSource and parses MP4 tracks', async () => {
    const source = createTorrentSource(Source, torrent, 0)
    expect(source._retrieveSize()).toBe(torrent.files[0].length)

    const input = new Input({ formats: ALL_FORMATS, source })

    const videoTrack = await input.getPrimaryVideoTrack()
    expect(videoTrack).toBeTruthy()
    expect(videoTrack!.codec).toBe('avc')

    let audioTrack = null
    try {
      audioTrack = await input.getPrimaryAudioTrack()
    } catch {
      // No audio track — fine for test
    }
    expect(audioTrack).toBeTruthy()
    expect(audioTrack!.codec).toBe('aac')

    const duration = Number(await videoTrack!.computeDuration())
    expect(duration).toBeGreaterThan(2)
    expect(duration).toBeLessThan(10)

    input.dispose()
  })

  it('builds keyframe index from TorrentSource', async () => {
    const source = createTorrentSource(Source, torrent, 0)
    const input = new Input({ formats: ALL_FORMATS, source })

    const videoTrack = (await input.getPrimaryVideoTrack())!
    const videoSink = new EncodedPacketSink(videoTrack)

    const keyframes: { timestamp: number; sequenceNumber: number }[] = []
    let packet = await videoSink.getKeyPacket(0, { metadataOnly: true })

    while (packet) {
      const ts = packet.timestamp
      if (Number.isFinite(ts) && ts >= 0) {
        keyframes.push({ timestamp: ts, sequenceNumber: packet.sequenceNumber })
      }
      const next = await videoSink.getNextKeyPacket(packet, { metadataOnly: true })
      if (!next || next.sequenceNumber === packet.sequenceNumber) break
      packet = next
    }

    expect(keyframes.length).toBeGreaterThan(0)
    expect(keyframes[0].timestamp).toBeCloseTo(0, 1)

    input.dispose()
  })

  it('collects segment packets from TorrentSource', async () => {
    const source = createTorrentSource(Source, torrent, 0)
    const input = new Input({ formats: ALL_FORMATS, source })

    const videoTrack = (await input.getPrimaryVideoTrack())!
    const videoSink = new EncodedPacketSink(videoTrack)
    const duration = Number(await videoTrack.computeDuration())

    const segmentEnd = Math.min(2, duration)
    const packets: EncodedPacket[] = []
    let pkt = await videoSink.getKeyPacket(0)
    if (!pkt) pkt = await videoSink.getFirstPacket()

    while (pkt) {
      if (pkt.timestamp >= segmentEnd) break
      if (!pkt.isMetadataOnly && pkt.timestamp >= 0) {
        packets.push(pkt)
      }
      const next = await videoSink.getNextPacket(pkt)
      if (!next || next.sequenceNumber === pkt.sequenceNumber) break
      pkt = next
    }

    expect(packets.length).toBeGreaterThan(0)
    for (const p of packets) {
      expect(p.data.byteLength).toBeGreaterThan(0)
    }

    input.dispose()
  })
})

// ─── Suite 2: Blocking reads during download ─────────────────────────────────

describe('Streaming with blocking reads', () => {
  let seederProc: ChildProcess
  let engine: BtEngine

  beforeAll(() => {
    // Ensure the long fixture exists (generate if missing)
    if (!existsSync(MP4_LONG)) {
      const script = join(FIXTURES_DIR, 'generate-fixtures.sh')
      execFileSync('bash', [script], { stdio: 'pipe' })
    }
  })

  afterAll(async () => {
    if (seederProc && !seederProc.killed) seederProc.kill('SIGTERM')
    if (engine) await engine.destroy()
  })

  it('parses MP4 while download is in progress (reads block on pieces)', async () => {
    // Throttle seeder upload to 50 KB/s and engine download to 50 KB/s.
    // 700KB file takes ~14s, plenty of time to observe blocking reads.
    const seeder = await startSeeder(MP4_LONG, 50 * 1024)
    seederProc = seeder.proc

    engine = createEngine({ downloadLimit: 50 * 1024 })
    const { torrent } = await engine.addTorrent(seeder.magnet)
    if (!torrent) throw new Error('Failed to add torrent')

    // Wait for torrent metadata + storage init (file list populated) but
    // NOT download completion. Metadata arrives from the seeder via BEP 9,
    // then initializeTorrentMetadata() runs asynchronously to set up storage.
    await new Promise<void>((resolve, reject) => {
      const timeout = setTimeout(() => reject(new Error('Metadata/storage init timeout')), 30000)
      const check = () => {
        if (torrent.files.length > 0) {
          clearTimeout(timeout)
          resolve()
        } else {
          setTimeout(check, 50)
        }
      }
      check()
    })

    // Track blocking behavior
    let setStreamingPiecesCalled = false
    const origSetStreamingPieces = torrent.setStreamingPieces.bind(torrent)
    torrent.setStreamingPieces = (pieces: Set<number> | null) => {
      setStreamingPiecesCalled = true
      return origSetStreamingPieces(pieces)
    }

    let anyReadBlocked = false
    const origWaitForPieces = torrent.waitForPieces.bind(torrent)
    torrent.waitForPieces = (pieceIndices: number[], signal?: AbortSignal) => {
      const missing = pieceIndices.filter((i) => !torrent.hasPiece(i))
      if (missing.length > 0) {
        anyReadBlocked = true
      }
      return origWaitForPieces(pieceIndices, signal)
    }

    // Record progress at parse start — with throttled seeder, download
    // should still be in progress
    const progressAtParseStart = torrent.completedPiecesCount
    const readStartedBeforeComplete = progressAtParseStart < torrent.piecesCount

    // Start parsing while download is in progress.
    // mediabunny's _read() calls will block via waitForPieces() until
    // the seeder delivers each piece.
    const source = createTorrentSource(Source, torrent, 0)
    const input = new Input({ formats: ALL_FORMATS, source })

    // getPrimaryVideoTrack() triggers _read() for the moov atom.
    // With throttled seeder, this will block until moov pieces arrive.
    const videoTrack = await input.getPrimaryVideoTrack()
    expect(videoTrack).toBeTruthy()
    expect(videoTrack!.codec).toBe('avc')

    // Build keyframe index while download may still be in progress
    const videoSink = new EncodedPacketSink(videoTrack!)
    const keyframes: { timestamp: number; sequenceNumber: number }[] = []
    let packet = await videoSink.getKeyPacket(0, { metadataOnly: true })
    while (packet) {
      const ts = packet.timestamp
      if (Number.isFinite(ts) && ts >= 0) {
        keyframes.push({ timestamp: ts, sequenceNumber: packet.sequenceNumber })
      }
      const next = await videoSink.getNextKeyPacket(packet, { metadataOnly: true })
      if (!next || next.sequenceNumber === packet.sequenceNumber) break
      packet = next
    }

    expect(keyframes.length).toBeGreaterThan(0)
    expect(keyframes[0].timestamp).toBeCloseTo(0, 1)

    // Read first segment's actual packet data (triggers mdat reads → blocking)
    const packets: EncodedPacket[] = []
    let pkt = await videoSink.getKeyPacket(0)
    if (!pkt) pkt = await videoSink.getFirstPacket()
    const segmentEnd = 2 // first 2 seconds
    while (pkt) {
      if (pkt.timestamp >= segmentEnd) break
      if (!pkt.isMetadataOnly && pkt.timestamp >= 0) {
        packets.push(pkt)
      }
      const next = await videoSink.getNextPacket(pkt)
      if (!next || next.sequenceNumber === pkt.sequenceNumber) break
      pkt = next
    }

    expect(packets.length).toBeGreaterThan(0)
    for (const p of packets) {
      expect(p.data.byteLength).toBeGreaterThan(0)
    }

    // Now wait for download to finish so cleanup is clean
    await waitForComplete(torrent, 60000)

    // ── Verify blocking behavior ──
    expect(setStreamingPiecesCalled).toBe(true)
    expect(readStartedBeforeComplete).toBe(true)
    expect(anyReadBlocked).toBe(true)

    input.dispose()
  }, 90000) // generous timeout for throttled download
})
