/**
 * Phase 1 E2E Integration Test: Video Streaming Pipeline
 *
 * Two test suites:
 *   1. "Sanity" — downloads small fixture fully, then parses (existing behavior)
 *   2. "Blocking reads" — starts parsing concurrently with a throttled download,
 *      proving that TorrentSource._read() blocks and resumes as pieces arrive.
 *
 * Prerequisites:
 *   - Python with libtorrent (uv sync in integration/python/)
 *   - test-h264-aac.mp4 fixture in integration/streaming/fixtures/
 *   - test-video-long.mp4 generated by fixtures/generate-fixtures.sh
 */
import { execFileSync, spawn, type ChildProcess } from 'node:child_process'
import { copyFileSync, existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import * as net from 'node:net'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, afterAll, beforeAll, describe, expect, it } from 'vitest'
import { ALL_FORMATS, EncodedPacketSink, Input, Source, type EncodedPacket } from 'mediabunny'

import { BtEngine } from '../../src/core/bt-engine'
import type { Torrent } from '../../src/core/torrent'
import type { PeerConnection } from '../../src/core/peer-connection'
import type { PeerAddress } from '../../src/core/swarm'
import { BLOCK_SIZE } from '../../src/core/active-piece'
import { InMemoryFileSystem, MemorySessionStore } from '../../src/adapters/memory'
import { NodeSocketFactory, NodeHasher, ScopedNodeFileSystem } from '../../src/adapters/node'
import { StorageRootManager } from '../../src/storage/storage-root-manager'
import { MemoryConfigHub } from '../../src/config/memory-config-hub'
import { createTorrentSource } from '../../src/streaming/torrent-source'

const FIXTURES_DIR = join(import.meta.dirname, 'fixtures')
const PYTHON_DIR = join(import.meta.dirname, '..', 'python')
const PYTHON_BIN = join(PYTHON_DIR, '.venv', 'bin', 'python')
const MP4_SMALL = join(FIXTURES_DIR, 'test-h264-aac.mp4')
const MP4_LONG = join(FIXTURES_DIR, 'test-video-long.mp4')
const UV_CACHE_DIR = join(tmpdir(), 'jstorrent-uv-cache')

interface SeederResult {
  proc: ChildProcess
  magnet: string
  infoHash: string
  port: number
}

interface ThrottledProxy {
  port: number
  close(): Promise<void>
}

interface StreamingDemandRecord {
  atMs: number
  token: string
  urgency: string
  pieces: number[]
}

interface DropRecord {
  atMs: number
  pieces: number[]
}

interface PieceCounters {
  requests: number
  cancels: number
  blocksReceived: number
  bytesReceived: number
  activations: number
  removals: number
}

interface TargetPieceSample {
  piece: number
  active: boolean
  complete: boolean
  requests: number
  cancels: number
  blocksReceived: number
  bytesReceived: number
  activations: number
  removals: number
}

interface TelemetrySample {
  atMs: number
  completedPieces: number
  targetPieces: TargetPieceSample[]
}

interface StreamingTelemetrySummary {
  demandHistory: StreamingDemandRecord[]
  dropHistory: DropRecord[]
  samples: TelemetrySample[]
  counters: Map<number, PieceCounters>
}

type IntegrationTorrentSource = InstanceType<typeof Source> & {
  _retrieveSize(): number
  _read(start: number, end: number, signal?: AbortSignal): Promise<unknown> | null
  _dispose(): void
  setCurrentSignal(signal: AbortSignal | null): void
}

type InstrumentedTorrent = Torrent & {
  _streamingScheduler: {
    buildPlan: (input: unknown) => {
      previousSuppressedPieces: Set<number>
      plan: { dropPieceIndices: number[] }
    }
  }
  requestPieces: (peer: PeerConnection, now: number) => void
  handleBlockCommon: (
    peer: PeerConnection,
    pieceIndex: number,
    blockOffset: number,
    dataLength: number,
    addBlockFn: (piece: unknown, blockIndex: number, peerId: string) => boolean,
  ) => void
}

/**
 * Start the Python seeder for a file.
 * @param file - Path to the file to seed
 * @param uploadLimit - Upload rate limit in bytes/sec (0 = unlimited)
 * @param pieceLength - Torrent piece length in bytes (optional)
 */
function startSeeder(file: string, uploadLimit = 0, pieceLength?: number): Promise<SeederResult> {
  return new Promise((resolve, reject) => {
    const args = [
      '-u', // Unbuffered stdout
      'seed_for_test.py',
      '--file',
      file,
      '--port',
      '0',
      '--host',
      '127.0.0.1',
      '--bind',
      '127.0.0.1',
      '--quiet',
    ]
    if (uploadLimit > 0) {
      args.push('--upload-limit', String(uploadLimit))
    }
    if (pieceLength) {
      args.push('--piece-length', String(pieceLength))
    }

    const proc = spawn(PYTHON_BIN, args, {
      cwd: PYTHON_DIR,
      env: {
        ...process.env,
        UV_CACHE_DIR,
      },
      stdio: ['ignore', 'pipe', 'pipe'],
    })

    let stdout = ''
    let stderr = ''

    proc.stdout!.on('data', (data: Buffer) => {
      stdout += data.toString()

      const magnetMatch = stdout.match(/^MAGNET_LOCALHOST=(.+)$/m)
      const hashMatch = stdout.match(/^INFOHASH=(.+)$/m)
      const portMatch = stdout.match(/^PORT=(.+)$/m)
      if (magnetMatch && hashMatch && portMatch) {
        resolve({
          proc,
          magnet: magnetMatch[1],
          infoHash: hashMatch[1],
          port: Number(portMatch[1]),
        })
      }
    })

    proc.stderr!.on('data', (data: Buffer) => {
      stderr += data.toString()
    })

    proc.on('error', (err) => {
      reject(new Error(`Failed to start seeder: ${err.message}`))
    })

    proc.on('exit', (code) => {
      if (code !== 0 && code !== null) {
        reject(new Error(`Seeder exited with code ${code}: ${stderr}`))
      }
    })

    setTimeout(() => {
      reject(new Error(`Seeder startup timeout. stdout: ${stdout}, stderr: ${stderr}`))
    }, 30000)
  })
}

function createEngine(opts?: { downloadLimit?: number; storageDir?: string }): BtEngine {
  const storageRootManager = new StorageRootManager((root) =>
    opts?.storageDir ? new ScopedNodeFileSystem(root.path) : new InMemoryFileSystem(),
  )
  if (opts?.storageDir) {
    storageRootManager.addRoot({ key: 'disk', label: 'Disk', path: opts.storageDir })
    storageRootManager.setDefaultRoot('disk')
  } else {
    storageRootManager.addRoot({ key: 'memory', label: 'Memory', path: '/memory' })
    storageRootManager.setDefaultRoot('memory')
  }

  let config: MemoryConfigHub | undefined
  if (opts?.downloadLimit) {
    config = new MemoryConfigHub({
      downloadSpeedUnlimited: false,
      downloadSpeedLimit: opts.downloadLimit,
    })
    void config.init()
  }

  return new BtEngine({
    socketFactory: new NodeSocketFactory(),
    storageRootManager,
    sessionStore: new MemorySessionStore(),
    hasher: new NodeHasher(),
    port: 0,
    config,
  })
}

function replacePeerHintPort(magnet: string, port: number): string {
  return magnet.replace(/x\.pe=127\.0\.0\.1:\d+/, `x.pe=127.0.0.1:${port}`)
}

async function startThrottledProxy(targetPort: number, rateBytesPerSec: number): Promise<ThrottledProxy> {
  return new Promise((resolve, reject) => {
    const server = net.createServer((clientSocket) => {
      const upstream = net.connect({ host: '127.0.0.1', port: targetPort })
      const downstreamQueue: Buffer[] = []
      let downstreamQueuedBytes = 0
      let destroyed = false
      let availableTokens = 0

      const cleanup = () => {
        if (destroyed) return
        destroyed = true
        clearInterval(flushTimer)
        clientSocket.destroy()
        upstream.destroy()
      }

      const flushTimer = setInterval(() => {
        if (destroyed) return

        availableTokens += Math.max(1, Math.floor(rateBytesPerSec / 20))
        while (downstreamQueue.length > 0 && availableTokens > 0) {
          const chunk = downstreamQueue[0]
          const toSend = Math.min(chunk.length, availableTokens)
          const slice = chunk.subarray(0, toSend)
          const wrote = clientSocket.write(slice)
          availableTokens -= toSend
          downstreamQueuedBytes -= toSend

          if (toSend === chunk.length) {
            downstreamQueue.shift()
          } else {
            downstreamQueue[0] = chunk.subarray(toSend)
          }

          if (!wrote) {
            break
          }
        }
      }, 50)

      clientSocket.on('data', (chunk) => {
        upstream.write(chunk)
      })
      upstream.on('data', (chunk: Buffer) => {
        downstreamQueue.push(Buffer.from(chunk))
        downstreamQueuedBytes += chunk.length
      })

      clientSocket.on('error', cleanup)
      upstream.on('error', cleanup)
      clientSocket.on('close', cleanup)
      upstream.on('close', cleanup)
      clientSocket.on('end', () => upstream.end())
      upstream.on('end', () => {
        const maybeFinish = setInterval(() => {
          if (downstreamQueuedBytes === 0) {
            clearInterval(maybeFinish)
            clientSocket.end()
          }
        }, 10)
      })
    })

    server.on('error', (error) => {
      reject(error)
    })

    server.listen(0, '127.0.0.1', () => {
      const address = server.address()
      if (!address || typeof address === 'string') {
        reject(new Error('Failed to determine throttled proxy port'))
        return
      }

      resolve({
        port: address.port,
        close: () =>
          new Promise<void>((resolveClose, rejectClose) => {
            server.close((error) => {
              if (error) rejectClose(error)
              else resolveClose()
            })
          }),
      })
    })
  })
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

async function waitForCondition(
  check: () => boolean,
  options?: { timeoutMs?: number; intervalMs?: number; label?: string },
): Promise<void> {
  const timeoutMs = options?.timeoutMs ?? 30000
  const intervalMs = options?.intervalMs ?? 50
  const startedAt = Date.now()

  while (Date.now() - startedAt < timeoutMs) {
    if (check()) return
    await sleep(intervalMs)
  }

  throw new Error(`Timed out waiting for ${options?.label ?? 'condition'}`)
}

function waitForComplete(torrent: Torrent, timeoutMs = 30000): Promise<void> {
  return new Promise<void>((resolve, reject) => {
    if (torrent.isComplete) {
      resolve()
      return
    }
    const timeout = setTimeout(
      () =>
        reject(
          new Error(
            `Download timeout. Progress: ${torrent.completedPiecesCount}/${torrent.piecesCount}`,
          ),
        ),
      timeoutMs,
    )
    torrent.on('complete', () => {
      clearTimeout(timeout)
      resolve()
    })
  })
}

function createMultiFileStreamingFixture(): { rootDir: string; videoName: string } {
  const rootDir = mkdtempSync(join(tmpdir(), 'jst-streaming-fixture-'))
  const prefixName = '000-prefix.bin'
  const videoName = '010-video.mp4'
  const prefixSize = 10 * 16_384

  writeFileSync(join(rootDir, prefixName), Buffer.alloc(prefixSize, 0x5a))
  copyFileSync(MP4_LONG, join(rootDir, videoName))

  return { rootDir, videoName }
}

function getMissingStartupPieces(
  torrent: Torrent,
  fileIndex: number,
  startupWindowPieces = 8,
): number[] {
  const pieceWindowLength = Math.min(
    torrent.files[fileIndex].length,
    torrent.pieceLength * startupWindowPieces,
  )
  const startupPieces = torrent.fileBytesToPieces(fileIndex, 0, pieceWindowLength)
  return startupPieces.filter((pieceIndex) => !torrent.hasPiece(pieceIndex))
}

function createPieceCounters(): PieceCounters {
  return {
    requests: 0,
    cancels: 0,
    blocksReceived: 0,
    bytesReceived: 0,
    activations: 0,
    removals: 0,
  }
}

function analyzeTargetPiece(
  samples: TelemetrySample[],
  pieceIndex: number,
): { activeTransitions: number; requestedWithoutReceiveSamples: number } {
  let activeTransitions = 0
  let requestedWithoutReceiveSamples = 0
  let previousActive: boolean | null = null

  for (const sample of samples) {
    const state = sample.targetPieces.find((piece) => piece.piece === pieceIndex)
    if (!state) continue

    if (previousActive !== null && previousActive !== state.active) {
      activeTransitions++
    }
    previousActive = state.active

    if (!state.complete && state.requests > 0 && state.blocksReceived === 0) {
      requestedWithoutReceiveSamples++
    }
  }

  return { activeTransitions, requestedWithoutReceiveSamples }
}

function getCompletionTimeMs(samples: TelemetrySample[], pieceIndex: number): number | null {
  for (const sample of samples) {
    const state = sample.targetPieces.find((piece) => piece.piece === pieceIndex)
    if (state?.complete) {
      return sample.atMs
    }
  }
  return null
}

function installStreamingTelemetry(
  torrent: Torrent,
  targetPieces: number[],
  sampleIntervalMs = 100,
): {
  demandHistory: StreamingDemandRecord[]
  dropHistory: DropRecord[]
  samples: TelemetrySample[]
  getPieceCounters: (pieceIndex: number) => PieceCounters
  stop: () => StreamingTelemetrySummary
} {
  const startedAt = Date.now()
  const demandHistory: StreamingDemandRecord[] = []
  const dropHistory: DropRecord[] = []
  const samples: TelemetrySample[] = []
  const counters = new Map<number, PieceCounters>()
  const restoreFns: Array<() => void> = []
  const wrappedPeers = new WeakSet<object>()
  let wrappedActivePieces: { getOrCreate: (index: number) => unknown; remove: (index: number) => void } | null =
    null

  const getCounters = (pieceIndex: number): PieceCounters => {
    let current = counters.get(pieceIndex)
    if (!current) {
      current = createPieceCounters()
      counters.set(pieceIndex, current)
    }
    return current
  }

  const maybeWrapActivePieces = (): void => {
    const activePieces = torrent.getActivePieceManager()
    if (!activePieces || activePieces === wrappedActivePieces) return

    wrappedActivePieces = activePieces

    const originalGetOrCreate = activePieces.getOrCreate.bind(activePieces)
    activePieces.getOrCreate = (index: number) => {
      const existed = activePieces.has(index)
      const piece = originalGetOrCreate(index)
      if (!existed && piece) {
        getCounters(index).activations++
      }
      return piece
    }
    restoreFns.push(() => {
      activePieces.getOrCreate = originalGetOrCreate
    })

    const originalRemove = activePieces.remove.bind(activePieces)
    activePieces.remove = (index: number) => {
      if (activePieces.has(index)) {
        getCounters(index).removals++
      }
      originalRemove(index)
    }
    restoreFns.push(() => {
      activePieces.remove = originalRemove
    })
  }

  const wrapPeer = (peer: PeerConnection): void => {
    if (wrappedPeers.has(peer)) return
    wrappedPeers.add(peer)

    const originalSendRequests = peer.sendRequests.bind(peer)
    peer.sendRequests = (requests) => {
      for (const request of requests) {
        getCounters(request.index).requests++
      }
      originalSendRequests(requests)
    }
    restoreFns.push(() => {
      peer.sendRequests = originalSendRequests
    })

    const originalSendCancel = peer.sendCancel.bind(peer)
    peer.sendCancel = (index: number, begin: number, length: number) => {
      getCounters(index).cancels++
      originalSendCancel(index, begin, length)
    }
    restoreFns.push(() => {
      peer.sendCancel = originalSendCancel
    })
  }

  for (const peer of torrent.peers) {
    wrapPeer(peer)
  }

  const instrumentedTorrent = torrent as InstrumentedTorrent

  const originalUpdateStreamingDemand = torrent.updateStreamingDemand.bind(torrent)
  torrent.updateStreamingDemand = (token, pieces, urgency) => {
    demandHistory.push({
      atMs: Date.now() - startedAt,
      token,
      urgency,
      pieces: pieces ? [...pieces].sort((a, b) => a - b) : [],
    })
    originalUpdateStreamingDemand(token, pieces, urgency)
  }
  restoreFns.push(() => {
    torrent.updateStreamingDemand = originalUpdateStreamingDemand
  })

  const originalBuildPlan = instrumentedTorrent._streamingScheduler.buildPlan.bind(
    instrumentedTorrent._streamingScheduler,
  )
  instrumentedTorrent._streamingScheduler.buildPlan = (input) => {
    const result = originalBuildPlan(input)
    if (result.plan.dropPieceIndices.length > 0) {
      dropHistory.push({
        atMs: Date.now() - startedAt,
        pieces: [...result.plan.dropPieceIndices].sort((a, b) => a - b),
      })
    }
    return result
  }
  restoreFns.push(() => {
    instrumentedTorrent._streamingScheduler.buildPlan = originalBuildPlan
  })

  const originalRequestPieces = instrumentedTorrent.requestPieces.bind(instrumentedTorrent)
  instrumentedTorrent.requestPieces = (peer, now) => {
    wrapPeer(peer)
    maybeWrapActivePieces()
    originalRequestPieces(peer, now)
  }
  restoreFns.push(() => {
    instrumentedTorrent.requestPieces = originalRequestPieces
  })

  const originalHandleBlockCommon = instrumentedTorrent.handleBlockCommon.bind(instrumentedTorrent)
  instrumentedTorrent.handleBlockCommon = (peer, pieceIndex, blockOffset, dataLength, addBlockFn) => {
    maybeWrapActivePieces()
    const beforePiece = torrent.getActivePieceManager()?.get(pieceIndex)
    const beforeBlocks = beforePiece?.blocksReceived ?? 0
    const beforeComplete = torrent.hasPiece(pieceIndex)

    originalHandleBlockCommon(peer, pieceIndex, blockOffset, dataLength, addBlockFn)

    const afterPiece = torrent.getActivePieceManager()?.get(pieceIndex)
    const afterBlocks = afterPiece?.blocksReceived ?? beforeBlocks
    const afterComplete = torrent.hasPiece(pieceIndex)

    if (afterBlocks > beforeBlocks || (!beforeComplete && afterComplete)) {
      const pieceCounters = getCounters(pieceIndex)
      pieceCounters.blocksReceived++
      pieceCounters.bytesReceived += dataLength
    }
  }
  restoreFns.push(() => {
    instrumentedTorrent.handleBlockCommon = originalHandleBlockCommon
  })

  const captureSample = () => {
    maybeWrapActivePieces()
    for (const peer of torrent.peers) {
      wrapPeer(peer)
    }

    samples.push({
      atMs: Date.now() - startedAt,
      completedPieces: torrent.completedPiecesCount,
      targetPieces: targetPieces.map((pieceIndex) => {
        const piece = torrent.getActivePieceManager()?.get(pieceIndex)
        const pieceCounters = getCounters(pieceIndex)
        return {
          piece: pieceIndex,
          active: piece !== undefined,
          complete: torrent.hasPiece(pieceIndex),
          requests: pieceCounters.requests,
          cancels: pieceCounters.cancels,
          blocksReceived: pieceCounters.blocksReceived,
          bytesReceived: pieceCounters.bytesReceived,
          activations: pieceCounters.activations,
          removals: pieceCounters.removals,
        }
      }),
    })
  }

  const sampleTimer = setInterval(() => {
    captureSample()
  }, sampleIntervalMs)

  return {
    demandHistory,
    dropHistory,
    samples,
    getPieceCounters: (pieceIndex: number) => getCounters(pieceIndex),
    stop: () => {
      clearInterval(sampleTimer)
      captureSample()
      for (const restore of restoreFns.reverse()) {
        restore()
      }
      return {
        demandHistory,
        dropHistory,
        samples,
        counters,
      }
    },
  }
}

async function runStartupReadSequence(
  source: IntegrationTorrentSource,
  pieceLength: number,
  windowCount: number,
): Promise<void> {
  const fileSize = source._retrieveSize()

  for (let windowIndex = 0; windowIndex < windowCount; windowIndex++) {
    const controller = new AbortController()
    source.setCurrentSignal(controller.signal)

    const start = windowIndex * pieceLength
    const end = Math.min(fileSize, start + pieceLength * 2)
    const result = source._read(start, end)
    expect(result).not.toBeNull()
    await result
  }

  source.setCurrentSignal(null)
}

// ─── Suite 1: Sanity (small fixture, download-then-parse) ────────────────────

describe('Streaming Pipeline E2E', () => {
  let seederProc: ChildProcess
  let engine: BtEngine
  let torrent: Torrent

  beforeAll(async () => {
    const seeder = await startSeeder(MP4_SMALL)
    seederProc = seeder.proc
    engine = createEngine()

    const { torrent: t } = await engine.addTorrent(seeder.magnet)
    if (!t) throw new Error('Failed to add torrent')
    torrent = t

    await waitForComplete(torrent)
  }, 45000)

  afterAll(async () => {
    if (seederProc && !seederProc.killed) seederProc.kill('SIGTERM')
    if (engine) await engine.destroy()
  })

  it('downloads the MP4 fixture completely', () => {
    expect(torrent.isComplete).toBe(true)
    expect(torrent.piecesCount).toBeGreaterThan(0)
    expect(torrent.completedPiecesCount).toBe(torrent.piecesCount)
    expect(torrent.files.length).toBe(1)
    expect(torrent.files[0].length).toBe(readFileSync(MP4_SMALL).length)
  })

  it('creates TorrentSource and parses MP4 tracks', async () => {
    const source = createTorrentSource(Source, torrent, 0)
    expect(source._retrieveSize()).toBe(torrent.files[0].length)

    const input = new Input({ formats: ALL_FORMATS, source })

    const videoTrack = await input.getPrimaryVideoTrack()
    expect(videoTrack).toBeTruthy()
    expect(videoTrack!.codec).toBe('avc')

    let audioTrack = null
    try {
      audioTrack = await input.getPrimaryAudioTrack()
    } catch {
      // No audio track — fine for test
    }
    expect(audioTrack).toBeTruthy()
    expect(audioTrack!.codec).toBe('aac')

    const duration = Number(await videoTrack!.computeDuration())
    expect(duration).toBeGreaterThan(2)
    expect(duration).toBeLessThan(10)

    input.dispose()
  })

  it('builds keyframe index from TorrentSource', async () => {
    const source = createTorrentSource(Source, torrent, 0)
    const input = new Input({ formats: ALL_FORMATS, source })

    const videoTrack = (await input.getPrimaryVideoTrack())!
    const videoSink = new EncodedPacketSink(videoTrack)

    const keyframes: { timestamp: number; sequenceNumber: number }[] = []
    let packet = await videoSink.getKeyPacket(0, { metadataOnly: true })

    while (packet) {
      const ts = packet.timestamp
      if (Number.isFinite(ts) && ts >= 0) {
        keyframes.push({ timestamp: ts, sequenceNumber: packet.sequenceNumber })
      }
      const next = await videoSink.getNextKeyPacket(packet, { metadataOnly: true })
      if (!next || next.sequenceNumber === packet.sequenceNumber) break
      packet = next
    }

    expect(keyframes.length).toBeGreaterThan(0)
    expect(keyframes[0].timestamp).toBeCloseTo(0, 1)

    input.dispose()
  })

  it('collects segment packets from TorrentSource', async () => {
    const source = createTorrentSource(Source, torrent, 0)
    const input = new Input({ formats: ALL_FORMATS, source })

    const videoTrack = (await input.getPrimaryVideoTrack())!
    const videoSink = new EncodedPacketSink(videoTrack)
    const duration = Number(await videoTrack.computeDuration())

    const segmentEnd = Math.min(2, duration)
    const packets: EncodedPacket[] = []
    let pkt = await videoSink.getKeyPacket(0)
    if (!pkt) pkt = await videoSink.getFirstPacket()

    while (pkt) {
      if (pkt.timestamp >= segmentEnd) break
      if (!pkt.isMetadataOnly && pkt.timestamp >= 0) {
        packets.push(pkt)
      }
      const next = await videoSink.getNextPacket(pkt)
      if (!next || next.sequenceNumber === pkt.sequenceNumber) break
      pkt = next
    }

    expect(packets.length).toBeGreaterThan(0)
    for (const p of packets) {
      expect(p.data.byteLength).toBeGreaterThan(0)
    }

    input.dispose()
  })
})

// ─── Suite 2: Blocking reads during download ─────────────────────────────────

describe('Streaming with blocking reads', () => {
  let seederProc: ChildProcess | null = null
  let secondarySeederProc: ChildProcess | null = null
  let throttledProxy: ThrottledProxy | null = null
  let engine: BtEngine | null = null
  let tempFixtureDir: string | null = null
  let tempDownloadDir: string | null = null

  beforeAll(() => {
    // Ensure the long fixture exists (generate if missing)
    if (!existsSync(MP4_LONG)) {
      const script = join(FIXTURES_DIR, 'generate-fixtures.sh')
      execFileSync('bash', [script], { stdio: 'pipe' })
    }
  })

  afterEach(async () => {
    if (seederProc && !seederProc.killed) seederProc.kill('SIGTERM')
    if (secondarySeederProc && !secondarySeederProc.killed) secondarySeederProc.kill('SIGTERM')
    if (engine) await engine.destroy()
    if (throttledProxy) await throttledProxy.close()
    if (tempFixtureDir) {
      rmSync(tempFixtureDir, { recursive: true, force: true })
    }
    if (tempDownloadDir) {
      rmSync(tempDownloadDir, { recursive: true, force: true })
    }
    seederProc = null
    secondarySeederProc = null
    throttledProxy = null
    engine = null
    tempFixtureDir = null
    tempDownloadDir = null
  })

  it('parses MP4 while download is in progress (reads block on pieces)', async () => {
    // Throttle seeder upload to 50 KB/s and engine download to 50 KB/s.
    // 700KB file takes ~14s, plenty of time to observe blocking reads.
    const seeder = await startSeeder(MP4_LONG, 50 * 1024)
    seederProc = seeder.proc

    engine = createEngine({ downloadLimit: 50 * 1024 })
    const { torrent } = await engine.addTorrent(seeder.magnet)
    if (!torrent) throw new Error('Failed to add torrent')

    // Wait for torrent metadata + storage init (file list populated) but
    // NOT download completion. Metadata arrives from the seeder via BEP 9,
    // then initializeTorrentMetadata() runs asynchronously to set up storage.
    await new Promise<void>((resolve, reject) => {
      const timeout = setTimeout(() => reject(new Error('Metadata/storage init timeout')), 30000)
      const check = () => {
        if (torrent.files.length > 0) {
          clearTimeout(timeout)
          resolve()
        } else {
          setTimeout(check, 50)
        }
      }
      check()
    })

    // Track blocking behavior
    let setStreamingPiecesCalled = false
    let updateStreamingDemandCalled = false
    const origSetStreamingPieces = torrent.setStreamingPieces.bind(torrent)
    torrent.setStreamingPieces = (pieces: Set<number> | null) => {
      setStreamingPiecesCalled = true
      return origSetStreamingPieces(pieces)
    }
    const origUpdateStreamingDemand = torrent.updateStreamingDemand.bind(torrent)
    torrent.updateStreamingDemand = (token, pieces, urgency) => {
      updateStreamingDemandCalled = true
      return origUpdateStreamingDemand(token, pieces, urgency)
    }

    let anyReadBlocked = false
    const origWaitForPieces = torrent.waitForPieces.bind(torrent)
    torrent.waitForPieces = (pieceIndices: number[], signal?: AbortSignal) => {
      const missing = pieceIndices.filter((i) => !torrent.hasPiece(i))
      if (missing.length > 0) {
        anyReadBlocked = true
      }
      return origWaitForPieces(pieceIndices, signal)
    }

    // Record progress at parse start — with throttled seeder, download
    // should still be in progress
    const progressAtParseStart = torrent.completedPiecesCount
    const readStartedBeforeComplete = progressAtParseStart < torrent.piecesCount

    // Start parsing while download is in progress.
    // mediabunny's _read() calls will block via waitForPieces() until
    // the seeder delivers each piece.
    const source = createTorrentSource(Source, torrent, 0)
    const input = new Input({ formats: ALL_FORMATS, source })

    // getPrimaryVideoTrack() triggers _read() for the moov atom.
    // With throttled seeder, this will block until moov pieces arrive.
    const videoTrack = await input.getPrimaryVideoTrack()
    expect(videoTrack).toBeTruthy()
    expect(videoTrack!.codec).toBe('avc')

    // Build keyframe index while download may still be in progress
    const videoSink = new EncodedPacketSink(videoTrack!)
    const keyframes: { timestamp: number; sequenceNumber: number }[] = []
    let packet = await videoSink.getKeyPacket(0, { metadataOnly: true })
    while (packet) {
      const ts = packet.timestamp
      if (Number.isFinite(ts) && ts >= 0) {
        keyframes.push({ timestamp: ts, sequenceNumber: packet.sequenceNumber })
      }
      const next = await videoSink.getNextKeyPacket(packet, { metadataOnly: true })
      if (!next || next.sequenceNumber === packet.sequenceNumber) break
      packet = next
    }

    expect(keyframes.length).toBeGreaterThan(0)
    expect(keyframes[0].timestamp).toBeCloseTo(0, 1)

    // Read first segment's actual packet data (triggers mdat reads → blocking)
    const packets: EncodedPacket[] = []
    let pkt = await videoSink.getKeyPacket(0)
    if (!pkt) pkt = await videoSink.getFirstPacket()
    const segmentEnd = 2 // first 2 seconds
    while (pkt) {
      if (pkt.timestamp >= segmentEnd) break
      if (!pkt.isMetadataOnly && pkt.timestamp >= 0) {
        packets.push(pkt)
      }
      const next = await videoSink.getNextPacket(pkt)
      if (!next || next.sequenceNumber === pkt.sequenceNumber) break
      pkt = next
    }

    expect(packets.length).toBeGreaterThan(0)
    for (const p of packets) {
      expect(p.data.byteLength).toBeGreaterThan(0)
    }

    // ── Verify blocking behavior ──
    expect(setStreamingPiecesCalled || updateStreamingDemandCalled).toBe(true)
    expect(readStartedBeforeComplete).toBe(true)
    expect(anyReadBlocked).toBe(true)

    input.dispose()
  }, 90000)

  it('keeps startup streaming pieces stable when start-of-file reads begin mid-download', async () => {
    const fixture = createMultiFileStreamingFixture()
    tempFixtureDir = fixture.rootDir
    tempDownloadDir = mkdtempSync(join(tmpdir(), 'jst-streaming-download-'))

    const seeder = await startSeeder(fixture.rootDir, 48 * 1024)
    seederProc = seeder.proc

    engine = createEngine({ downloadLimit: 48 * 1024, storageDir: tempDownloadDir })
    const { torrent } = await engine.addTorrent(seeder.magnet)
    if (!torrent) throw new Error('Failed to add torrent')

    await waitForCondition(() => torrent.files.length > 0, {
      timeoutMs: 30000,
      label: 'torrent metadata + storage init',
    })

    const videoFileIndex = torrent.files.findIndex((file) => file.path.includes(fixture.videoName))
    expect(videoFileIndex).toBeGreaterThanOrEqual(0)

    await waitForCondition(
      () => torrent.completedPiecesCount >= 4 && getMissingStartupPieces(torrent, videoFileIndex).length >= 2,
      {
        timeoutMs: 45000,
        label: 'bulk progress before streaming start',
      },
    )

    const targetPieces = getMissingStartupPieces(torrent, videoFileIndex).slice(0, 2)
    expect(targetPieces).toHaveLength(2)

    const completedAtStreamStart = torrent.completedPiecesCount
    const telemetry = installStreamingTelemetry(torrent, targetPieces)
    const source = createTorrentSource(Source, torrent, videoFileIndex) as IntegrationTorrentSource

    const readPromise = runStartupReadSequence(source, torrent.pieceLength, 6)
    await waitForCondition(() => telemetry.demandHistory.length > 0, {
      timeoutMs: 15000,
      label: 'streaming demand to start',
    })

    await sleep(8000)
    await readPromise
    source._dispose()

    const summary = telemetry.stop()
    const completedAfterObservation =
      summary.samples[summary.samples.length - 1]?.completedPieces ?? torrent.completedPiecesCount

    await waitForComplete(torrent, 60000)

    expect(summary.demandHistory.length).toBeGreaterThan(0)
    expect(completedAfterObservation).toBeGreaterThan(completedAtStreamStart)

    const targetDropCount = summary.dropHistory.reduce(
      (count, drop) => count + drop.pieces.filter((piece) => targetPieces.includes(piece)).length,
      0,
    )
    expect(targetDropCount).toBeLessThanOrEqual(4)

    for (const pieceIndex of targetPieces) {
      const counters = summary.counters.get(pieceIndex) ?? createPieceCounters()
      const analysis = analyzeTargetPiece(summary.samples, pieceIndex)

      expect(counters.requests).toBeGreaterThan(0)
      expect(counters.blocksReceived).toBeGreaterThan(0)
      expect(counters.requests).toBeLessThan(10)
      expect(counters.cancels).toBeLessThan(6)
      expect(analysis.activeTransitions).toBeLessThan(6)
      expect(analysis.requestedWithoutReceiveSamples).toBeLessThan(20)
    }
  }, 150000)

  it('rescues the first startup piece with duplicate requests when a fast peer appears', async () => {
    const fixture = createMultiFileStreamingFixture()
    tempFixtureDir = fixture.rootDir
    tempDownloadDir = mkdtempSync(join(tmpdir(), 'jst-streaming-download-'))
    const rescuePieceLength = 256 * 1024

    const slowSeeder = await startSeeder(fixture.rootDir, 0, rescuePieceLength)
    seederProc = slowSeeder.proc
    throttledProxy = await startThrottledProxy(slowSeeder.port, 4 * 1024)

    engine = createEngine({ storageDir: tempDownloadDir })
    const { torrent } = await engine.addTorrent(replacePeerHintPort(slowSeeder.magnet, throttledProxy.port))
    if (!torrent) throw new Error('Failed to add torrent')

    await waitForCondition(() => torrent.files.length > 0, {
      timeoutMs: 30000,
      label: 'torrent metadata + storage init',
    })

    const videoFileIndex = torrent.files.findIndex((file) => file.path.includes(fixture.videoName))
    expect(videoFileIndex).toBeGreaterThanOrEqual(0)

    await waitForCondition(() => torrent.peers.length >= 1, {
      timeoutMs: 15000,
      label: 'slow peer connection',
    })

    const firstFilePiece = torrent.fileBytesToPieces(videoFileIndex, 0, 1)[0]
    const targetPiece = getMissingStartupPieces(torrent, videoFileIndex, 1)[0]
    if (targetPiece === undefined) {
      throw new Error('Expected a missing startup piece before triggering streaming read')
    }
    expect(torrent.hasPiece(targetPiece)).toBe(false)

    const targetOffset = (targetPiece - firstFilePiece) * torrent.pieceLength
    const telemetry = installStreamingTelemetry(torrent, [targetPiece], 50)
    const source = createTorrentSource(Source, torrent, videoFileIndex) as IntegrationTorrentSource

    const readPromise = source._read(targetOffset, targetOffset + 1024)
    expect(readPromise).not.toBeNull()

    await waitForCondition(() => telemetry.getPieceCounters(targetPiece).requests > 0, {
      timeoutMs: 5000,
      label: 'initial slow-peer startup request',
    })

    const fastSeeder = await startSeeder(fixture.rootDir, 0, rescuePieceLength)
    secondarySeederProc = fastSeeder.proc
    torrent.addPeerHints([{ ip: '127.0.0.1', port: fastSeeder.port, family: 'ipv4' } satisfies PeerAddress])

    await waitForCondition(() => torrent.peers.length >= 2, {
      timeoutMs: 15000,
      label: 'fast peer connection',
    })

    await readPromise
    source._dispose()

    const summary = telemetry.stop()
    const counters = summary.counters.get(targetPiece) ?? createPieceCounters()
    const completionTimeMs = getCompletionTimeMs(summary.samples, targetPiece)
    const blocksPerPiece = Math.ceil(torrent.pieceLength / BLOCK_SIZE)

    expect(counters.requests).toBeGreaterThan(blocksPerPiece)
    expect(counters.cancels).toBeGreaterThanOrEqual(1)
    expect(counters.blocksReceived).toBeGreaterThanOrEqual(1)
    expect(completionTimeMs).not.toBeNull()
    expect(completionTimeMs!).toBeLessThan(15000)
  }, 90000)
})
